name: Deploy Next.js site to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  WORKDIR: my-portfolio       # folder that contains the Next.js app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.WORKDIR }}/package-lock.json

      - name: Configure GitHub Pages helper
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKDIR }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('my-portfolio/package-lock.json') }}-${{ hashFiles('my-portfolio/**/*.[jt]s', 'my-portfolio/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('my-portfolio/package-lock.json') }}-

      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: npm ci

      - name: Build (static export via output:export)
        working-directory: ${{ env.WORKDIR }}
        run: npx --no-install next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WORKDIR }}/out    # generated by next build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
