# .github/workflows/nextjs.yml
name: Deploy Next.js site to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  WORKDIR: my-portfolio          # ← folder that contains package.json / next.config.js

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Set up Node + npm cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ env.WORKDIR }}/package-lock.json

      # 3) (Optional) Configure Pages helper – rewrites basePath & disables server–image opt
      - name: Configure GitHub Pages for Next.js
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      # 4) Cache .next build artifacts between runs
      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ env.WORKDIR }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('my-portfolio/package-lock.json') }}-${{ hashFiles('my-portfolio/**/*.[jt]s', 'my-portfolio/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('my-portfolio/package-lock.json') }}-

      # 5) Install dependencies (npm ci) inside the app directory
      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: npm ci

      # 6) Build & export static site
      - name: Build with Next.js
        working-directory: ${{ env.WORKDIR }}
        run: |
          npx --no-install next build
          npx --no-install next export

      # 7) Upload the exported `out` folder as an artifact for the deploy job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WORKDIR }}/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
